name: Recovering secrets 

# Assumption:
# You've created the following GitHub secrets in your repository:
# MY_CLIENT_ID - encode/decode with base64 - useful for private repositories

on:
  push:
  workflow_dispatch:

jobs:
  base64:
    name: Recover With Base64
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - env:
          DOMAIN: ${{secrets.SOUSHUBA_HOSTNAME}}
          USERNAME: ${{secrets.SOUSHUBA_USERNAME}}
          PASSWD: ${{secrets.SOUSHUBA_PASSWORD}}
        run: |
          echo "SOUSHUBA_HOSTNAME (base64)    = $(echo ${SOUSHUBA_HOSTNAME} | base64)"
          echo "SOUSHUBA_USERNAME (base64) = $(echo ${SOUSHUBA_USERNAME} | base64)"
          echo "SOUSHUBA_PASSWORD (base64) = $(echo ${SOUSHUBA_PASSWORD} | base64)"  
          echo "Copy the above value, and then execute locally:"
  
